name: Build TB303 Distortion for All Platforms

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Create JuceLibraryCode symlinks (Windows)
      run: |
        mkdir JuceLibraryCode
        mklink /J JuceLibraryCode\modules JUCE\modules
        
        echo #include "../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp" > JuceLibraryCode\include_juce_audio_plugin_client_VST3.cpp
        echo #include "../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp" > JuceLibraryCode\include_juce_audio_plugin_client_Standalone.cpp
        
        echo namespace BinaryData {} > JuceLibraryCode\BinaryData.cpp
        echo #pragma once > JuceLibraryCode\BinaryData.h
        echo namespace BinaryData {} >> JuceLibraryCode\BinaryData.h
    
    - name: Build Windows VST3
      run: |
        cd Builds\VisualStudio2022
        msbuild TB303Distortion_SharedCode.vcxproj /p:Configuration=Release /p:Platform=x64 /maxcpucount
        msbuild TB303Distortion_VST3ManifestHelper.vcxproj /p:Configuration=Release /p:Platform=x64 /maxcpucount  
        msbuild TB303Distortion_VST3.vcxproj /p:Configuration=Release /p:Platform=x64 /maxcpucount
    
    - name: Upload Windows VST3
      uses: actions/upload-artifact@v4
      with:
        name: TB303Distortion-Windows-VST3
        path: Builds/VisualStudio2022/x64/Release/VST3/TB303Distortion.vst3
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create JuceLibraryCode symlinks (macOS)
      run: |
        mkdir -p JuceLibraryCode
        ln -sf ../JUCE/modules JuceLibraryCode/modules
        
        echo '#include "../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp"' > JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp
        echo '#include "../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp"' > JuceLibraryCode/include_juce_audio_plugin_client_Standalone.cpp
        
        echo 'namespace BinaryData {}' > JuceLibraryCode/BinaryData.cpp
        printf '#pragma once\nnamespace BinaryData {}' > JuceLibraryCode/BinaryData.h
    
    - name: Build macOS VST3 and AU
      run: |
        cd Builds/MacOSX
        xcodebuild -project TB303Distortion.xcodeproj -scheme "TB303Distortion - VST3" -configuration Release ARCHS="arm64 x86_64" VALID_ARCHS="arm64 x86_64" clean build
        xcodebuild -project TB303Distortion.xcodeproj -scheme "TB303Distortion - AU" -configuration Release ARCHS="arm64 x86_64" VALID_ARCHS="arm64 x86_64" build
    
    - name: Upload macOS VST3
      uses: actions/upload-artifact@v4
      with:
        name: TB303Distortion-macOS-VST3
        path: Builds/MacOSX/build/Release/TB303Distortion.vst3
        if-no-files-found: error
        
    - name: Upload macOS AU
      uses: actions/upload-artifact@v4
      with:
        name: TB303Distortion-macOS-AU
        path: Builds/MacOSX/build/Release/TB303Distortion.component
        if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libasound2-dev libjack-jackd2-dev \
                            libfreetype6-dev libx11-dev libxcomposite-dev \
                            libxcursor-dev libxext-dev libxinerama-dev \
                            libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev \
                            libglu1-mesa-dev mesa-common-dev
                            
    - name: Create JuceLibraryCode symlinks
      run: |
        mkdir -p JuceLibraryCode
        ln -sf ../JUCE/modules JuceLibraryCode/modules
        
        # Create include files for VST3 and Standalone
        echo '#include "../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp"' > JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp
        echo '#include "../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp"' > JuceLibraryCode/include_juce_audio_plugin_client_Standalone.cpp
        
        # Create minimal BinaryData files
        echo 'namespace BinaryData {}' > JuceLibraryCode/BinaryData.cpp
        echo '#pragma once\nnamespace BinaryData {}' > JuceLibraryCode/BinaryData.h
    
    - name: Build Linux VST3
      run: |
        cd Builds/LinuxMakefile
        make CONFIG=Release VST3 -j$(nproc)
    
    - name: Upload Linux VST3
      uses: actions/upload-artifact@v4
      with:
        name: TB303Distortion-Linux-VST3
        path: Builds/LinuxMakefile/build/TB303Distortion.vst3
        if-no-files-found: error

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Prepare release assets
      run: |
        # Create zip files for macOS assets
        cd TB303Distortion-macOS-VST3
        zip -r ../TB303Distortion-macOS-VST3.zip TB303Distortion.vst3
        cd ../TB303Distortion-macOS-AU
        zip -r ../TB303Distortion-macOS-AU.zip TB303Distortion.component
        cd ..
        
        # Copy Windows and Linux assets
        cp TB303Distortion-Windows-VST3/TB303Distortion.vst3 TB303Distortion-Windows.vst3 2>/dev/null || echo "Windows VST3 not found"
        cp TB303Distortion-Linux-VST3/TB303Distortion.vst3 TB303Distortion-Linux.vst3 2>/dev/null || echo "Linux VST3 not found"
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: TB303 Distortion v${{ github.run_number }}
        body: |
          🎵 TB303 Distortion Plugin - Cross-Platform Release
          
          ## 📦 Downloads:
          - **Windows**: TB303Distortion-Windows.vst3 (for Bitwig, Cubase, etc.)
          - **macOS**: TB303Distortion-macOS-VST3.zip + TB303Distortion-macOS-AU.zip (VST3 + AU)
          - **Linux**: TB303Distortion-Linux.vst3 (for Bitwig, Reaper, etc.)
          
          ## ✨ Features:
          - Animated Acid Smiley (morphs with distortion)
          - TB-303 Style Distortion Effect
          - Embedded Resources (no external files needed)
          - MIDI Parameter Automation
          
          ## 📥 Installation:
          - **Windows**: Copy .vst3 to `C:\Program Files\Common Files\VST3\`
          - **macOS**: Copy .vst3 to `~/Library/Audio/Plug-Ins/VST3/` and .component to `~/Library/Audio/Plug-Ins/Components/`
          - **Linux**: Copy .vst3 to `~/.vst3/` or `/usr/lib/vst3/`
        files: |
          TB303Distortion-Windows.vst3
          TB303Distortion-macOS-VST3.zip
          TB303Distortion-macOS-AU.zip
          TB303Distortion-Linux.vst3
        draft: false
        prerelease: false